name: yesod-page-cursor
version: 2.0.1.0
github: "freckle/yesod-page-cursor"
license: MIT
author: Freckle Engineering
maintainer: engineering@freckle.com
copyright: "2020 Renaissance Learning Inc"

extra-doc-files:
  - README.md
  - ChangeLog.md

description: Cursor based pagination for Yesod

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - http-link-header
  - text
  - unliftio
  - yesod-core

library:
  source-dirs: src
  dependencies:
    - containers
    - network-uri

tests:
  readme:
    main: README.lhs
    ghc-options: -pgmL markdown-unlit
    dependencies:
      - markdown-unlit
      - persistent
      - time
      - yesod-core
      - yesod-page-cursor

  yesod-page-cursor-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - hspec-expectations-lifted
      - http-types
      - lens
      - lens-aeson
      - monad-logger
      - mtl
      - persistent
      - persistent-sqlite
      - persistent-template
      - scientific
      - time
      - unliftio-core
      - wai-extra
      - yesod
      - yesod-page-cursor
      - yesod-test
