name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack-yaml:
          - stack.yaml           # ghc-9.0
          - stack-lts-18.28.yaml # ghc-8.10
          - stack-lts-16.31.yaml # ghc-8.8
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@v2
        with:
          stack-yaml: ${{ matrix.stack-yaml }}
      - uses: freckle/stack-action@v3
        with:
          stack-yaml: ${{ matrix.stack-yaml }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rwe/actions-hlint-setup@v1
      - uses: rwe/actions-hlint-run@v2
        with:
          fail-on: warning

  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@v2
        with:
          stack-yaml: stack-nightly.yaml
      - uses: freckle/stack-action@v3
        with:
          stack-yaml: stack-nightly.yaml
          stack-arguments: --resolver nightly
